name: Deploy Angular App to Nginx on Ubuntu

on:
  push:
    branches:
      - bc # Change this to your main branch d

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular App
        run: ng build

      - name: Copy configuration file
        run: cp -f ./src/assets/configs/configs-bc.json ./src/assets/configs/configs.json

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan brain-itek.com >> ~/.ssh/known_hosts
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to VPS via SSH f
        run: |
          ssh martin@brain-itek.com 'bash -s' << 'EOF'
            cd /var/www
            sudo mkdir -p bc-martsco-client
            cd bc-martsco-client
            sudo rm -rf *
          EOF
          cd dist/martsco-client && ls
          sudo scp -r ./** martin@brain-itek.com:/var/www/bc-martsco-client/
      # - name: Restart Nginx Service
      #   run: |
      #     ssh root@brain-itek.com 'bash -s' << 'EOF'
      #       sudo systemctl reload nginx
      #     EOF
