name: Deploy Angular App to Nginx on Ubuntu

on:
  push:
    branches:
      - bc # Change this to your main branch d

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular App
        run: ng build

      - name: Configure SSH f
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan brain-itek.com >> ~/.ssh/known_hosts
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to VPS via SSH
        run: |
          ssh root@brain-itek.com 'bash -s' << 'EOF'
            cd /var/www/bc-martsco-client
            rm -rf *
          EOF
          cd dist/martsco-client && ls
          scp -r ./** root@brain-itek.com:/var/www/bc-martsco-client/
      # - name: Restart Nginx Service
      #   run: |
      #     ssh root@brain-itek.com 'bash -s' << 'EOF'
      #       sudo systemctl reload nginx
      #     EOF
